presidio-oss/cline-based-code-generator

src/core/webview/ClineProvider.ts, webview-ui/src/components/settings/ApiOptions.tsx
Issue Reason: We are storing all the credentials in both the global and workspace secrets. When the credentials are not found in the workspace, it defaults to the global value.
Fix: …
=> Fixed issue in AWS Bedrock session token

src/core/webview/ClineProvider.ts
- After retrieving the workspace folder path, a condition is added to verify its presence. If the condition is met, the File Watcher is initialized, as passing an empty value to the File Watcher leads this issues.
- Additionally, the codeIndexBackground function is brought under this condition, as invoking it without a valid workspace folder path serves no purpose.
-   [x] Tests are passing (`npm test`) and code is …
=> Fixed extension host termination issue

src/integrations/workspace/HaiFileSystemWatcher.ts, webview-ui/src/components/settings/ApiOptions.tsx, webview-ui/src/components/settings/EmbeddingOptions.tsx
- useDeepCompareEffect performs a deep equality check on dependencies, preventing effect re-runs when object references change but the content remains the same.
- Validation now only occurs when the actual configuration values change, not during unrelated state updates. …
=> Fixed LLM and embedding validation occurs for every indexing update

.github/workflows/release.yml, package.json
Removed Open VSX Registry publish, can be added later based on the internal discussion
=> Removed Open VSX Registry publish

CHANGELOG.md, src/integrations/code-prep/CodeContextAddition.ts, webview-ui/src/components/settings/ApiOptions.tsx
- The encoding logic for "gpt-4o" was causing failures, resulting in code context error and workspace restoration alerts.
- Token calculation operations were blocking the main thread, preventing extension UI from loading properly. …
=> Error during code context and indexing

.github/workflows/release-dev.yml, .github/workflows/release.yml
Added the following permissions to development and marketplace releases.
- `contents: write`, `packages: write`, `checks: write`, and `pull-requests: write`.
=> Fix permissions issue in release-dev.yml and release.yml for reusable workflow

src/core/webview/ClineProvider.ts, src/shared/ExtensionMessage.ts, webview-ui/src/components/chat/CustomInstructionsMenu.tsx, webview-ui/src/components/settings/SettingsView.tsx, webview-ui/src/components/settings/SettingsViewExtra.tsx
- Fixed custom instructions showing "undefined" when vscode is opened without a workspace
- Disabled custom instructions, code context, code indexing when no workspace is opened
=> Fixed undefined issue in custom instructions

src/utils/runtime-downloader.ts
- Added `await` to the extraction of the faiss-node build to prevent potential issues where indexing might occur before the extraction is complete.
=> Could not import faiss-node

.changeset/friendly-masks-marry.md, src/core/webview/ClineProvider.ts
Added a flag to prevent code indexing from being triggered multiple times simultaneously, which may be causing users to encounter limit exceeded errors even for smaller project sizes.
=> Fixed multiple code indexing background tasks being triggered

.changeset/weak-geckos-turn.md, package-lock.json, src/core/webview/ClineProvider.ts, webview-ui/src/App.tsx, webview-ui/src/components/chat/ChatTextArea.tsx, webview-ui/src/components/settings/ApiOptions.tsx, webview-ui/src/components/settings/EmbeddingOptions.tsx, webview-ui/src/components/settings/OpenRouterModelPicker.tsx, webview-ui/src/components/settings/SettingsView.tsx
This feature introduces autosave for all settings.
- The previous validation, which was triggered only when clicking the Done button, has been replaced with an asterisk (*) to indicate required fields.
- The remaining validation sequence remains unchanged.
- **In the previous version:**
if a required field was cleared and the user navigated away without clicking Done, the change wouldn’t be saved. However, if Done was clicked, a required field error would be displayed.
**In the current version:**
Clearing a required field will remove its value from both the workspace and global state, and the change will be automatically saved.
Gist on file-wise changes: 
- ClineProvider: Refactored LLM and Embedding state updates into a reusable function and added required field validation to prevent …
=> Autosave settings

.changeset/lazy-lies-smash.md, src/core/webview/ClineProvider.ts, webview-ui/src/components/settings/SettingsViewExtra.tsx
- The Code Index notification appears when code indexing is enabled (default: Yes) and the progress is at 0% (i.e., indexing has not started yet).
- The notification provides three options:
* Open Settings: Navigates the user to the settings screen.
* No: Disables code indexing, preventing future notifications.
* Cancel: Closes the notification without making any changes.
- Once code indexing has started or completed, the notification will no longer appear.
- A warning note has been added to inform users about the data usage of code indexing.
-   [ ] 📚 …
=> Add code indexing notification with user controls and a privacy warning

package.json, src/integrations/inline-editing/index.ts
- Toggle Inline Editing Option for HAI from Advanced Settings (Redirects to VS Code Settings of HAI)
-   [] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [] Tests are passing (`npm test`) and code is formatted and linted (`npm run format && npm run lint`)
-   [] I have reviewed [contributor guidelines](https://github.com/presidio-oss/cline-based-code-generator/blob/main/CONTRIBUTING.md)
Linked Issue: https://github.com/presidio-oss/cline-based-code-generator/issues/69
=> feat: add inline editing configuration option for hai

.changeset/many-peaches-speak.md, src/core/Cline.ts, src/core/prompts/system.hai.ts, src/core/prompts/system.hai.v1.ts, src/core/prompts/system.hai.v2.ts, src/core/prompts/system.hai.v3.ts, src/shared/customApi.ts, webview-ui/src/components/settings/SettingsViewExtra.tsx, webview-ui/src/interfaces/hai-context.interface.ts
This PR adds system prompt optimization capabilities to the HAI Build code generator. It introduces a new feature that allows users to select different system prompt versions, each optimized for different performance characteristics and API cost savings.
The implementation includes:
1. A new dropdown in the settings UI for selecting system prompt versions
2. Four different system prompt optimization levels:
- **Precision**: Reduces API cost by ~40%
- **Clarity**: Reduces API cost by ~30%
- **Harmony**: Reduces API cost by ~60%
- **Standard**: Default with no optimizations (highest API cost)
3. Modular system prompt architecture with version-specific implementations
This feature helps users optimize their API costs while maintaining appropriate levels of performance for their specific use …
=> Add system prompt optimization with version selection

.github/workflows/release-dev.yml
The issue was that the coverage report artifact was uploaded instead of the VSIX package.
-   [x] I have reviewed [contributor guidelines](https://github.com/presidio-oss/cline-based-code-generator/blob/main/CONTRIBUTING.md …
=> fix: fixed issue in github artifact pushed to teams

webview-ui/src/components/settings/SettingsView.tsx
Removed embedding configuration from the plan/act toggle card since we won't have different models used for embeddings based on the mode …
=> fix: removed embedding from plan/act toggle card in settings

.changeset/bright-dots-appear.md, src/core/task/index.ts
=> fix: fixed find-files-agent returned empty files even after indexing

.changeset/strange-ducks-deny.md, esbuild.js, src/core/storage/state.ts, webview-ui/src/components/common/TelemetryBanner.tsx, webview-ui/src/components/settings/ApiOptions.tsx, webview-ui/src/components/settings/SettingsView.tsx, webview-ui/src/components/settings/SettingsViewExtra.tsx
Fixed and added the following:
- Fixed issue in esbuild (Added a dummy api-key)
- Enabled prompt caching for Bedrock
- Set v3 as default prompt in settings
- Analytics info update …
=> fix: v3 and prompt caching been set as default and fixed the issue in esbuild

.changeset/modern-spies-explain.md, src/core/prompts/system.hai.v1.ts, src/core/prompts/system.hai.v2.ts, src/core/prompts/system.hai.v3.ts
fixes rename plan_mode_response to plan_mode_respond due to upstream tool changes introduced in https://github.com/presidio-oss/cline-based-code-generator/pull/88/files#diff-ec5bfb97fa984921dcb420c3fcf9747854c3302ac5ec437f1fe604ee68fc4e7a …
=> fix: rename plan_mode_response to plan_mode_respond

src/shared/haiDefaults.ts
Fixing a typo in default prompt.
https://github.com/presidio-oss/cline-based-code-generator/issues/103
-   [ ] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [x] I have reviewed [contributor guidelines](https://github.com/presidio-oss/cline-based-code-generator/blob/main/CO …
=> Fix typo on default prompt

.changeset/sharp-eels-accept.md, src/extension.ts
Fixed inline editing issue in versions 3.3.1 and above
Reason and Fix:
The `WebviewProvider.getVisibleInstance()` returned undefined during startup. To resolve this, the `sidebarWebview` instance was used directly to access the controller. …
=> fix: fixed inline edit not working

.vscodeignore
Included the experts folder in .vscodeignore so that it will be preserved during the build process and used to load the default experts in the application. …
=> fix: included experts directory in build for default expert loading

.changeset/lovely-avocados-do.md, src/core/controller/index.ts, src/shared/ExtensionMessage.ts, src/shared/WebviewMessage.ts, webview-ui/src/App.tsx, webview-ui/src/components/chat/ChatView.tsx, webview-ui/src/components/hai/HaiStoryAccordion.tsx, webview-ui/src/components/hai/HaiTaskComponent.tsx, webview-ui/src/components/hai/hai-tasks-list.tsx, webview-ui/src/components/welcome/QuickActions.tsx, webview-ui/src/interfaces/hai-task.interface.ts
- When user selected Hai task successfully executes, the chat window prompts the user with confirmation message asking whether they wish to mark the task as `Completed`. Two buttons are presented beneath the confirmation prompt to accept or to decline the prompt.
- If the user confirms the prompt, a new field named `status` with the value `Completed` is added to the task object in the corresponding PRD feature JSON file.
- If the user declines, no changes are made to the PRD feature files, and the confirmation prompt is simply hidden.
- If the user is not satisfied with the execution result and continues the conversation via chat, all subsequent messages will be considered as part of the currently selected Hai task. Once satisfied, the user can manually mark the task as `Completed`.
- …
=> feat: implement feature to mark tasks as 'Completed' after successful execution

.changeset/happy-seals-roll.md, webview-ui/src/components/chat/ChatTextArea.tsx
- Fixed expert icon rendering to prevent application crash when iconComponent is missing, with fallback to default person icon …
=> fix : expert icon rendering with fallback to default icon

.changeset/long-coats-swim.md, src/core/prompts/custom.ts, src/embedding/providers/openai.ts
- Revised the guidelines and usage prompt for the find_relevant_files tool to clarify that it should be used when the query pertains to the current project and not for general queries. …
=> fix: prevent unnecessary find_relevant_files tool call

.changeset/hungry-timers-happen.md, webview-ui/src/components/chat/ChatView.tsx
- Resolved an issue where clicking on chat-related quick action tiles did not populate the message input with the corresponding task. …
=> fix : quick action tile

.changeset/serious-queens-fry.md, src/core/storage/state.ts, webview-ui/src/components/settings/ApiOptions.tsx
Enablement of prompt cache by default may cause minor issues in some scenarios.
=> fix : default prompt cache

.changeset/seven-jeans-watch.md, src/core/storage/state.ts, webview-ui/src/components/settings/SettingsView.tsx
Storing the usage report preference globally to avoid prompting the user for it in every new project. This improves user experience by respecting their initial choice across all projects.
-   [x] I have reviewed …
=> fix: send report preference

.changeset/perfect-mugs-hope.md, src/core/controller/index.ts, webview-ui/src/components/chat/ChatView.tsx, webview-ui/src/components/settings/SettingsView.tsx
Update the settings interface to remove autosave functionality and introduce a 'Done' button that users can click to confirm and save their changes. This will improve the user experience by making the save action more deliberate and visible. …
=> fix: save button implementation in settings

src/extension.ts
Settings value changes should reflect only after done when moving to another tab
=> fix: navigation issue

.changeset/lovely-geese-listen.md, src/api/providers/openai.ts
The reason for replacing `baseUrl` with `endpoint` in AzureOpenAI is that when using `baseUrl`, users need to manually append `/openai` to the endpoint `(e.g., https://<azure-domain>.com/openai)`. In contrast, when using `endpoint`, this is handled automatically and the additional path is not required.
-   [x] Tests are passing (`npm test`) …
=> fix: Replaced baseUrl with endpoint for AzureOpenAI

.changeset/new-knives-reflect.md, src/core/controller/index.ts, src/core/storage/state.ts, src/global-constants.ts, src/integrations/workspace/HaiFileSystemWatcher.ts, src/services/posthog/PostHogClientProvider.ts, src/services/posthog/telemetry/TelemetryService.ts, src/shared/ExtensionMessage.ts, src/shared/WebviewMessage.ts, src/shared/hai-config.ts, webview-ui/src/components/settings/SettingsView.tsx, webview-ui/src/components/welcome/WelcomeView.tsx, webview-ui/src/context/ExtensionStateContext.tsx
This PR introduces support for external telemetry configuration overrides via a `.hai.config` file placed at the root of the workspace.
Users can define a `.hai.config` file to override default telemetry settings that may be injected through CI/CD pipelines. This enables environment-specific customization.
Supported override parameters:
```
langfuse.apiUrl=
langfuse.apiKey=
langfuse.publicKey=
posthog.url=
posthog.apiKey=
```
- .hai.config is not git-excluded by default. Please ensure sensitive keys are not committed unintentionally.
- The config is parsed at runtime and merged with the default telemetry configuration.
-   [ ] 💥 Breaking change (fix or feature …
=> Add .hai.config to support external overrides for telemetry configuration

README.md
Updated the README to include a Telemetry and Documentation section, detailing how to configure a custom Langfuse and PostHog setup, along with comprehensive documentation for the HAI Code Generator.
-   [ ] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [ ] I have created a changeset …
=> doc: updated readme with telemetry override and wiki info

.changeset/three-numbers-cough.md, .github/workflows/release.yml, src/core/controller/index.ts, src/core/experts/ExpertManager.ts, src/core/task/index.ts, src/extension.ts, webview-ui/src/components/experts/ExpertsView.tsx
- Resolved an issue where LLM validation could become stuck in the welcome state, preventing further progress.
- Added information to guide users on embedding configuration when Deepcrawl is enabled.
-   [x] I have created a changeset …
=> fix: LLM validation hangs on welcome state

README.md, docs/features/cormatrix-integration.md
Updated all instances of "CorMatrix" to "COR-Matrix" in README and integration guide for consistency and clarity. This change enhances the accuracy of references to the integration feature.
-   [ ] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [ ] I have created a changeset using `npm …
=> fix: Standardize naming from CorMatrix to COR-Matrix in documentation

.changeset/real-items-occur.md, esbuild.js
- Resolved the langfuse trace not found issue by configuring environment variables in esbuild.js to include the langfuse keys during the build process. …
=> fix: langfuse trace not found 

.changeset/fair-buttons-chew.md, package-lock.json, package.json, proto/models.proto, src/api/providers/anthropic.ts, src/api/providers/bedrock.ts, src/api/transform/openrouter-stream.ts, src/core/controller/models/refreshOpenRouterModels.ts, src/core/controller/models/refreshRequestyModels.ts, src/shared/api.ts, src/shared/proto/models.ts, src/utils/cost.ts, webview-ui/src/components/chat/Announcement.tsx, webview-ui/src/components/settings/ApiOptions.tsx
- Enhanced support for Claude Sonnet 4, extending its maximum context window to 1 million tokens and enabling tiered pricing for more flexible usage models. …
=> feat: Enhance Claude Sonnet 4 support with 1M context window and tiered pricing

src/extension.ts, src/services/posthog/telemetry/TelemetryService.ts, webview-ui/src/components/settings/providers/embedding/BedrockEmbeddingProvider.tsx, webview-ui/src/components/settings/sections/AboutSection.tsx
- Fix dropdown layering issues in BedrockEmbeddingProvider by setting an appropriate zIndex on DropdownContainer.
- Initialize langfuse during extension activation
-   [ ] Changes are limited to a single feature, bugfix, or chore (split larger changes into separate PRs)
-   [ ] I have created a changeset using `npm run changeset` (required …
=> fix: Set zIndex for DropdownContainer in BedrockEmbeddingProvider and initialize langfuse during extension activation

.changeset/kind-games-remain.md, .github/ISSUE_TEMPLATE/bug_report.yml, hai-docs/getting-started/model-selection-guide.mdx, hai-docs/getting-started/understanding-context-management.mdx, hai-docs/provider-config/anthropic.mdx, src/core/api/providers/anthropic.ts, src/core/api/providers/bedrock.ts, src/core/api/transform/openrouter-stream.ts, src/core/controller/models/refreshOpenRouterModels.ts, src/extension.ts, src/shared/api.ts, webview-ui/src/components/settings/OpenRouterModelPicker.tsx, webview-ui/src/components/settings/providers/AnthropicProvider.tsx, webview-ui/src/components/settings/providers/BedrockProvider.tsx, webview-ui/src/components/settings/providers/ClaudeCodeProvider.tsx
- Enhanced support for Claude Sonnet 4.5, extending its maximum context window to 1 million tokens and enabling tiered pricing for more flexible usage models. …
=> feat: Enhance Claude Sonnet 4.5 support with 1M context window and tiered pricing
