presidio-oss/cline-based-code-generator

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
Below are the changes/addition:
1. Added vscode configuration
2. Added issue and pr template for github
please let me know if there are any changes to be made. Thanks!
> chore: added .vscode and .github

- .github/workflows/test.yml
NA
Added github workflow for validating merge requests
> Added github workflow for validating merge requests (only main branch)

- src/core/Cline.ts
- src/core/webview/ClineProvider.ts
NA
Renamed .clinerules as .hairules
> Renamed .clinerules as .hairules

- CHANGELOG.md
- webview-ui/src/components/common/CopyClipboard.tsx
- webview-ui/src/components/hai/DetailedView.tsx
- webview-ui/src/components/hai/HaiTaskComponent.tsx
1. Added: Copy to clipboard functionality for HAI tasks in both the global story view and detailed view.
2. Updated: Changelog to include the previous Bedrock issue.
> Added copy to clipboard for HAI tasks

- .github/workflows/sync.yml
- .github/workflows/test.yml
- webview-ui/src/components/hai/DetailedView.tsx
- webview-ui/src/components/hai/HaiTaskComponent.tsx
Added github workflow to sync changes from github to gitlab (main branch alone) and also fixed the following issues
Issues:
- Replaced vscode test with mock build for merge request checks
- Fixed string concatenation warning …
> Added github workflow for syncing changes from github to gitlab

- .github/workflows/test.yml
- Added the workflow_call in test yml 
> Added the workflow_call in test yml

- .changeset/friendly-masks-marry.md
- .changeset/strong-files-repeat.md
- .changeset/witty-colts-smell.md
- CHANGELOG.md
- package.json
> Changelog update for the new release v3.1.0

- .github/workflows/test.yml
- webview-ui/src/components/settings/SettingsView.tsx
- Removed an unused variable in SettingsView that was causing the dev pipeline to fail.
- Added a mock build in the test pipeline to prevent build issues in the dev and prod pipelines. …
> Removed unused variable and added mock build in test pipeline

- package-lock.json
- webview-ui/src/components/settings/SettingsViewExtra.tsx
-   [ ] I have reviewed [contributor guidelines](https://github.com/presidio-oss/cline-based-code-generator/blob/main/CONTRIBUTING.md)
> fix: updated prompt description

- .changeset/many-peaches-speak.md
- .changeset/young-candles-smash.md
- CHANGELOG.md
- package.json
- Updated changelog and version in package.json
> Prepare for release v3.2.0

- .changeset/fair-tigers-cry.md
- CHANGELOG.md
- package.json
> Prepare for release v3.3.0

- .changeset/bright-dots-appear.md
- .changeset/strange-ducks-deny.md
- CHANGELOG.md
- package-lock.json
- package.json
> Prepare for release v3.3.2

- package-lock.json
> fix: updated package-lock

- .changeset/modern-spies-explain.md
- .changeset/shy-hats-jump.md
- CHANGELOG.md
- package-lock.json
- package.json
> Prepare for release v3.4.0

- .changeset/happy-seals-roll.md
- CHANGELOG.md
- package-lock.json
- package.json
> Prepare for release v3.4.2

- .changeset/plenty-jars-begin.md
- src/core/controller/index.ts
- src/core/storage/state.ts
The welcome-view component does not render when resetting the application state.
> fix: welcome view

- CHANGELOG.md
- package-lock.json
- package.json
Prepare for release v3.5.0
-   [ ] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [x] I have reviewed [contributor guidelines](https://github.com/presidio-oss/cline-based-code-generator/blob/m …
> Prepare for release v3.5.0

- .changeset/lovely-geese-listen.md
- CHANGELOG.md
- package-lock.json
- package.json
Prepare for release v3.5.1
-   [x] I have reviewed [contributor guidelines](https://github.com/presidio-oss/cline-based-code-generator/blob/m …
> Prepare for release v3.5.1

- .github/workflows/release-dev.yml
- package-lock.json
- package.json
- Updated hai-guardrails version to fix the pino transport issue
- Updated node version for the dev pipeline
-   [x] I have reviewed …
> fix: Updated hai-guardrails and node version for dev pipeline

- src/core/prompts/system.hai.v1.ts
- src/core/prompts/system.hai.v2.ts
- src/core/prompts/system.hai.v3.ts
Updated the following details in the v1, v2 and v3 prompt
- Added `newtask` tool and its example
- Added `load_mcp_documentation` tool
- Updated `addUserInstructions` function
-   [ ] I have created a changeset using `npm run changeset` …
> fix: Updated v1, v2, and v3 prompt

- .changeset/bright-clouds-drop.md
- .changeset/tall-rockets-greet.md
- .github/workflows/release.yml
- CHANGELOG.md
- package-lock.json
- package.json
> Prepare for release v3.7.0

- .changeset/light-laws-grab.md
- src/shared/embeddings.ts
- src/shared/validate.ts
- webview-ui/src/components/chat/ChatTextArea.tsx
- webview-ui/src/components/experts/ExpertsView.tsx
- webview-ui/src/components/settings/EmbeddingOptions.tsx
- Added support for Titan Embedding V2 in Bedrock model selection.
- Made embedding configuration as completely optional with `None` option …
> feat : Embedding configuration enhancement

- .changeset/fast-baboons-smell.md
- src/core/controller/mcp/downloadMcp.ts
- Enhances the MCP installation process by allowing the download and installation of MCPs from local , in addition to existing support for remote sources. …
> fix: Enhance MCP download function to support local MCP retrieval

- .changeset/serious-bobcats-wash.md
- src/core/controller/index.ts
- webview-ui/src/components/mcp/configuration/tabs/marketplace/McpMarketplaceCard.tsx
- webview-ui/src/components/mcp/configuration/tabs/marketplace/McpMarketplaceView.tsx
- Allows users to install custom MCPs by providing their own manifests or configuration sources. …
> fix: Enhance MCP marketplace to support custom MCPs installation
